# Generated by Django 5.0.6 on 2024-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_galleryimages_alter_customuser_nominee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DSES_idcard',
            field=models.BooleanField(default=False),
        ),
    ]
