# Generated by Django 5.0.6 on 2024-08-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_customuser_dses_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood',
            field=models.CharField(default='O+', max_length=10),
        ),
    ]
