# Generated by Django 5.0.6 on 2024-08-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guardian',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
